flight_status_immediate_response = {
    'action': 'flight.check',
    'allRequiredParamsPresent': True,
    'diagnosticInfo': {'webhook_latency_ms': 829.0},
     'fulfillmentMessages': [{'text': {'text': ['']}}],
     'intent': {'displayName': 'flight.status',
                'name': 'projects/flights-e717c/agent/intents/1cac474e-e32f-465d-8712-594226e5baae'},
     'intentDetectionConfidence': 0.8100000023841858,
     'languageCode': 'en',
     'outputContexts': [{'lifespanCount': 3,
                         'name': 'projects/flights-e717c/agent/sessions/twitter_e87bd064-6864-4626-aa12-732c1b62df15/contexts/check-flight',
                         'parameters': {'airline': '',
                                        'airline.original': '',
                                        'airport': [],
                                        'airport.original': '',
                                        'airport_from': '',
                                        'airport_from.original': '',
                                        'airport_to': '',
                                        'airport_to.original': '',
                                        'date': '2018-11-12T12:00:00-05:00',
                                        'date.original': 'tomorrow?',
                                        'flight-number': 'BW 600',
                                        'flight-number.original': 'BW600',
                                        'from': '',
                                        'from.original': '',
                                        'to': '',
                                        'to.original': ''}}],
     'parameters': {'airline': '',
                    'airport': [],
                    'airport_from': '',
                    'airport_to': '',
                    'date': '2018-11-12T12:00:00-05:00',
                    'flight-number': 'BW 600',
                    'from': '',
                    'to': ''},
     'queryText': 'What is the status of flight BW600 tomorrow?'}


flight_status_webhook_response = {
    'originalDetectIntentRequest': {'payload': {}},
    'queryResult': {'action': 'flight.status',
                 'allRequiredParamsPresent': True,
                 'fulfillmentMessages': [{'text': {'text': ['']}}],
                 'intent': {'displayName': 'flight.status',
                            'name': 'projects/flights-e717c/agent/intents/1cac474e-e32f-465d-8712-594226e5baae'},
                 'intentDetectionConfidence': 0.81,
                 'languageCode': 'en',
                 'outputContexts': [{'lifespanCount': 3,
                                     'name': 'projects/flights-e717c/agent/sessions/twitter_e87bd064-6864-4626-aa12-732c1b62df15/contexts/check-flight',
                                     'parameters': {'airline': '',
                                                    'airline.original': '',
                                                    'airport': [],
                                                    'airport.original': '',
                                                    'airport_from': '',
                                                    'airport_from.original': '',
                                                    'airport_to': '',
                                                    'airport_to.original': '',
                                                    'date': '2018-11-12T12:00:00-05:00',
                                                    'date.original': 'tomorrow?',
                                                    'flight-number': 'BW 600',
                                                    'flight-number.original': 'BW600',
                                                    'from': '',
                                                    'from.original': '',
                                                    'to': '',
                                                    'to.original': ''}}],
                 'parameters': {'airline': '',
                                'airport': [],
                                'airport_from': '',
                                'airport_to': '',
                                'date': '2018-11-12T12:00:00-05:00',
                                'flight-number': 'BW 600',
                                'from': '',
                                'to': ''},
                 'queryText': 'What is the status of flight BW600 tomorrow?'},
 'responseId': '7b2d0327-edf9-4030-ba46-394ff211f8ed',
 'session': 'projects/flights-e717c/agent/sessions/twitter_e87bd064-6864-4626-aa12-732c1b62df15'}

flight_status_cal_response = {
    '1': {
           'arr_city': 'Port of Spain',
           'arr_code': 'POS',
           'arr_time_local': '2018-11-12T11:30:00',
           'arr_time_utc': '2018-11-12T15:30:00',
           'dept_city': 'Georgetown',
           'dept_code': 'GEO',
           'dept_time_local': '2018-11-12T10:20:00',
           'dept_time_utc': '2018-11-12T14:20:00',
           'flight_number': '600',
           'flight_status': 'Scheduled',
           'id': '363000',
           'sta_local': '2018-11-12T11:30:00',
           'sta_utc': '2018-11-12T15:30:00',
           'std_local': '2018-11-12T10:20:00',
           'std_utc': '2018-11-12T14:20:00'
          },
        '2': {
               'arr_city': 'Toronto',
               'arr_code': 'YYZ',
               'arr_time_local': '2018-11-12T18:15:00',
               'arr_time_utc': '2018-11-12T23:15:00',
               'dept_city': 'Port of Spain',
               'dept_code': 'POS',
               'dept_time_local': '2018-11-12T13:10:00',
               'dept_time_utc': '2018-11-12T17:10:00',
               'flight_number': '600',
               'flight_status': 'Scheduled',
               'id': '363001',
               'sta_local': '2018-11-12T18:15:00',
               'sta_utc': '2018-11-12T23:15:00',
               'std_local': '2018-11-12T13:10:00',
               'std_utc': '2018-11-12T17:10:00'}}